Mongey/terraform-provider-kafka

README.md, kafka/client.go, kafka/provider.go, kafka/provider_test.go, kafka/resource_kafka_topic.go, kafka/resource_kafka_topic_test.go
=> Rename brokers to bootstrap_servers

README.md, kafka/client.go, kafka/provider.go
=> TLS Support

README.md, kafka/client.go, kafka/provider.go
=> Add SASL support

go.mod, go.sum, kafka/config.go
This way if multiple connections need to be made we create a new
connection for each
=> scram connection to use a generator function

kafka/migrate_kafka_acl_state.go, kafka/migrate_kafka_acl_state_test.go, kafka/resource_kafka_acl.go
=> Migrate ACL state

website/docs/index.html.markdown, website/docs/r/acl.html.markdown, website/docs/r/topic.html.markdown, website/kafka.erb
=> Adding a website folder for the documentation to following normal convention

kafka/client.go
Should fix https://github.com/Mongey/terraform-provider-kafka/issues/77
=> Fail if client certificate is not correct instead of showing drift

README.md
Options available at https://kafka.apache.org/documentation/#brokerconfigs
=> Update docs on `configs`

kafka/client.go
=> Return error if replication factor cannot be determined

kafka/config.go, kafka/lazy_client.go, kafka/provider.go, kafka/provider_test.go, kafka/resource_kafka_acl.go, kafka/resource_kafka_acl_test.go, kafka/resource_kafka_topic.go, kafka/resource_kafka_topic_test.go
Potential fix for #100 and #95 . Needs more testing
=> Lazy client

kafka/resource_kafka_topic.go
=> Validate partitions and replication_factor values

examples/main.tf
This PR fixes the issue reported in #67 
After applying, I do a plan and it works as expected now.
```console
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
kafka_topic.syslog: Refreshing state... [id=syslog8]
kafka_acl.global: Refreshing state... [id=User:*|*|All|Allow|Topic|*|Literal]
kafka_acl.test1: Refreshing state... [id=User:Alice|*|Read|Allow|Topic|syslog8|Literal]
------------------------------------------------------------------------
No changes. Infrastructure is up-to-date.
This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be …
```
=> Avoid locking down access to topic when run locally (fixes #67).

kafka/client.go, kafka/config.go, kafka/lazy_client.go, kafka/provider.go
=> Don't print sensitive values

kafka/config.go, kafka/config_test.go, kafka/provider.go
=> Fix TLS config 

.goreleaser.yml
https://www.terraform.io/docs/registry/providers/publishing.html#manually-preparing-a-release
=> Update build settings to be compatible with Terraform 0.13

.github/workflows/release.yml, .github/workflows/snapshot.yml, .github/workflows/test.yml, go.mod, kafka/resource_kafka_topic.go
=> Update to Go 1.16; Build for darwin/arm64

kafka/client.go, kafka/client_test.go
=> Fix crash when kafka client does not have bootstrap_servers set

README.md
Minor update to dev guide - added missing command.
=> Minor update to dev guide

kafka/client.go, kafka/config.go
Improves performance
Fixes #225
=> Fetch metadata for a single topic rather than all topics

kafka/lazy_client.go, kafka/lazy_init_test.go, kafka/provider_test.go, kafka/resource_kafka_quota_test.go, kafka/resource_kafka_topic.go
Fixes #250 
Fixes #178 
Fixes #189
=> Allow plans when connection to Kafka cannot be established

kafka/client.go, website/docs/index.html.markdown, website/docs/r/acl.html.markdown, website/docs/r/quota.html.markdown
* Added a RWMutex around topics updates. No tests added because I didn't find a reliable way to reproduce the bug. I could reproduce it by adding a small delay in the update loop (20ms) to increase the chance of trigger but not sure how to make a test of that.
https://github.com/Mongey/terraform-provider-kafka/blob/0813b8d9bf8727cd1d84438e6a28a77edf371964/kafka/client.go#L188-L190
* Also updated docs (env var alternative, required/optional) + added doc regarding quota
Fixes #216
=> fix: concurrent map writes during topics updates

.github/workflows/debug.yaml
=> Add debug workflow

.github/workflows/release.yml, .github/workflows/snapshot.yml, .github/workflows/test.yml
https://github.com/actions/cache/blob/main/examples.md#go---modules
=> Bump actions/cache to v4

README.md, kafka/config.go, kafka/provider.go, kafka/resource_kafka_quota_test.go
=> Add OAuth Scope Support

.github/workflows/test.yml, kafka/client.go, kafka/config.go, kafka/data_source_kafka_topic.go, kafka/data_source_kafka_topic_test.go, kafka/kafka_acls.go, kafka/kafka_quotas.go, kafka/kafka_user_scram_credentials.go, kafka/migrate_kafka_acl_state.go, kafka/provider_test.go, kafka/resource_kafka_acl.go, kafka/resource_kafka_acl_test.go, kafka/resource_kafka_topic.go, kafka/resource_kafka_user_scram_credential.go, kafka/topic.go
golangci-lint-action@v6 is latest version that uses golint 1.x
=> Fix reported golint errors 

kafka/kafka_acls.go
Fixing the support for DelegationToken. Convertion from ACLResource to string was pending :') 
Error:
```terraform
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "kafka_acl" "consumer_read" {
+ acl_host                     = "*"
+ acl_operation                = "Read"
+ acl_permission_type          = "Allow"
+ acl_principal                = "User:consumer-service"
+ id                           = (known after apply)
+ resource_name                = "orders"
+ resource_pattern_type_filter = "Literal"
+ resource_type                = "Topic"
}
+ resource "kafka_acl" "delegated" {
+ acl_host                     = "*"
+ acl_operation …
```
=> fix: DelegationToken Resource
