.gitignore
kafka/provider.go
kafka/resource_kafka_topic.go
kafka/utils.go
vendor/github.com/Shopify/sarama/alter_configs_request.go
vendor/github.com/Shopify/sarama/alter_configs_response.go
vendor/github.com/Shopify/sarama/broker.go
vendor/github.com/Shopify/sarama/request.go
vendor/vendor.json

Update configs rather than recreating topics

---

kafka/provider.go
kafka/resource_kafka_topic.go

* Increases the default timeout for all operations from 90s to 120s.
* Increases the default time for config changes from 10s -> 120s
* Uses provider specified timeout when waiting for config updates
Fixes #26

Make config update timeout configurable, increase timeouts

---

README.md

A small PR to fix descriptions of kafka_acl properties in README.

fix kafka_acl descriptions in README

---

kafka/resource_kafka_topic.go

If a config value contains a non-string value, Terraform will now error
with the following message.
```
Error: Error loading tmp.tf: Error reading config for kafka_topic[test]:
At 12:24: root.config[0].cleanup.policy: unknown type for string
*ast.LiteralType
```
Fixes #41

Ensure config values are always strings.

---

.circleci/config.yml
kafka/client.go
kafka/client_test.go
kafka/topic.go

This uses the broker information to see what version of `DescribeConfigRequest` to use.
Addresses #44

Generate request version from broker information

---

README.md
kafka/config.go
kafka/provider.go
kafka/resource_kafka_acl_test.go

to allow for more use cases, such as if cert was stored in vault

allow certs to be provided as strings or file path

---

kafka/client.go

The error: 
```
2019-11-21T16:51:42.498+0100 [DEBUG] plugin.terraform-provider-kafka: 2019/11/21 16:51:42 [ERROR] Error refreshing metadata kafka server: Request was for a topic or partition that does not exist on this broker.
2019-11-21T16:51:42.498+0100 [DEBUG] plugin.terraform-provider-kafka: 2019/11/21 16:51:42 [ERROR] Error getting topics kafka server: Request was for a topic or partition that does not exist on this broker. from Kafka
2019/11/21 16:51:42 [ERROR] root: eval: *terraform.EvalRefresh, err: kafka_topic.test_topic: kafka server: Request was for a topic or partition that does not exist on this broker.
2019/11/21 16:51:42 [ERROR] root: eval: *terraform.EvalSequence, err: kafka_topic.test_topic: kafka server: Request was for a topic or partition that does not exist on this …
```

Handle usecase when kafka returns ErrUnknownTopicOrPartition error gracefully

---

kafka/kafka_acls.go

When there are a lot of ACLs, Kafka or Sarama may not respond for a
while when calling RefreshMetadata a lot.
Seen when querying for 500 ACLs on CC.

Stop calling RefreshMetadata for ACLs.

---

kafka/kafka_acls.go

This fixes a nil dereference segfault on kafka_acl plan in some scenarios:
```
Stack trace from the terraform-provider-kafka_v0.4.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xeef939]
goroutine 41 [running]:
github.com/Mongey/terraform-provider-kafka/kafka.(*Client).ListACLs(0xc0005b2450, 0x0, 0x0, 0x0, 0x0, 0x6b)
/home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/kafka_acls.go:424 +0x499
github.com/Mongey/terraform-provider-kafka/kafka.(*LazyClient).ListACLs(0xc00057f890, 0x15, 0xc0006436f0, 0x1, 0x1, 0xc000042718)
/home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/lazy_client.go:138 +0x79 …
```

Fix nil dereference error in kafka_acl plan

---

README.md

This is to make it clear in documentation when in addition to Root CA is used a chain of intermediate/subordinate CAs.
Original issue described in #272.

Update documentation when TLS is used with chain of CAs

---

examples/main.tf

Example main.tf was failing when trying to send to the docker-compose stack with: 
`Error: kafka: client has run out of available brokers to talk to: remote error: tls: bad certificate`
With this change it work OK.

Fix example TF file which was failing with a TLS error

---

kafka/kafka_acls.go
kafka/resource_kafka_acl.go

This is related to my issue #285 - disclaimer: I'm not really a go/terraform dev
Digging around the code I've discovered that the method `aclRead` does not set the `PatternType` (`Literal`, `Prefix`, ...) for the acls returned by kafka (maybe it's intentional? i don't know, looks wrong to me).
In the sample manifest from my issue, the ACL from Kafka (`aclID.String()`) is serialized to the following string:
```
User:CN=user|192.168.1.2|Read|Allow|Topic|test_topic|
```
While the ACL read from the state (`a.String()`) is: 
```
User:CN=user|192.168.1.2|Read|Allow|Topic|test_topic|Literal
```
Because of this, when comparing the two acls, the `exact match` [check](https://github.com/Mongey/terraform-provider-kafka/blob/55b7619d34970cc8a46b59aa8a6114a79312b82e/kafka/resource_kafka_acl.go#L132) …

fix: aclRead does not read PatternType of acl already in Kafka

---

kafka/kafka_acls.go
kafka/resource_kafka_acl_test.go

Closes #237 
When the ACL has already been removed from kafka, and terraform destroy is executed, the error occurs:
```
Error: There were no acls matching this filter
```
This suggestion is to avoid this error

Fix remove acls when not exist

---

GNUmakefile
kafka/data_source_kafka_topic_test.go
kafka/lazy_init_test.go
kafka/provider_test.go
kafka/resource_kafka_acl_test.go
kafka/resource_kafka_quota_test.go
kafka/resource_kafka_topic_test.go

Happy holidays!
This PR greatly speeds up testing by running tests in parallel. Before the change `make testacc` was always timing out as it would've taken 12 minutes to complete all tests serially. This is due to the tests needing to run many Terraform commands, which are very slow. These tests are safe to run in parallel as they are using UUIDs for resource names. After the change it takes less than 3 minutes to run them (tested on M1 max machine).
```
> make testacc
.
.
.
--- PASS: TestAcc_TopicAlterReplicationFactor (145.34s)
PASS
ok      github.com/Mongey/terraform-provider-kafka/kafka        147.024s
```
A couple of other changes were also included:
- Fix failing tests due to nil dereference on [this line](https://github.com/Mongey/terraform-provider-kafka/blob/6218bcac5c374e47de1680 …

fix and parallelize acceptance tests

---

README.md
kafka/config.go
kafka/kafka_user_scram_credentials.go
kafka/lazy_client.go
kafka/provider.go
kafka/resource_kafka_user_scram_credential.go
kafka/resource_kafka_user_scram_credential_test.go

Issue https://github.com/Mongey/terraform-provider-kafka/issues/64
Used the changes in this closed PR as a starting point https://github.com/Mongey/terraform-provider-kafka/pull/207 
Worth noting that the ID for a credential is (username, SCRAM mechanism) as a single username can be associated with multiple credentials.
```
> kafka-configs.sh --bootstrap-server localhost:9092 --command-config kafka.properties --describe --entity-type users
SCRAM credential configs for user-principal 'donovan' are SCRAM-SHA-256=iterations=4096, SCRAM-SHA-512=iterations=4096
```

add SCRAM user credential resource

---

kafka/config.go

This PR creates a  Go `net/proxy` `Dialer` with the [`FromEnvironment`](https://pkg.go.dev/golang.org/x/net/proxy#FromEnvironment) method and passes it in the Kafka client configuration under `Net.Proxy`. This allows users to configure a proxy client from environment variables (for example using `ALL_PROXY`). If no environment variable is set, the proxy will be transparent, making this PR backwards-compatible.
For more safety, we could place this code under a condition on an extra configuration key (`use_proxy`, or specify explicitly the proxy configuration in the provider configuration). However, I've inspired this from [the PostgreSQL provider's proxy support](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/website/docs/index.html.markdown#socks5-proxy-support) …

feat(config): Use a proxy dialer

---

kafka/resource_kafka_quota.go

We are using this provider to maintain kafka resources, including quotas.  
When creating and updating quotas is fails in 90% of cases because the provider creates it in kafka, and then immediately queries for it, but it doesn't find it at this point, as it seems it takes a little bit of time to appear in Kafka.
Here are the logs we were getting for such a scenario:
```
[INFO] Alter quota: timestamp="2024-02-19T12:46:14.578+0200"
[TRACE] Alter Quota Request &{0 [{[{user 0 User:CN=dev-enablement/test-tf-apply}] [{request_percentage 100 false} {consumer_byte_rate 5.24288e+06 false} {producer_byte_rate 5.24288e+06 false}]}] false}: timestamp="2024-02-19T12:46:14.578+0200"
[TRACE] ThrottleTime: 0: timestamp="2024-02-19T12:46:15.178+0200"
[INFO] Reading Quota: …
```

fix: wait for quota state after creation

---

kafka/topic.go

Fix unexpected diff when kafka broker has cluster-wide config.
This patch for #407.

Add SourceDynamicDefaultBroker as a type to refuse to retrieve topic settings

---

README.md
kafka/resource_kafka_user_scram_credential.go

Hello @Mongey!
This PR is related to https://github.com/Mongey/terraform-provider-kafka/issues/349
I've add import for kafka_user_scram_credential resource.

Add SCRAM user credentials import

---

go.mod
go.sum
kafka/config.go
kafka/provider.go

This is required to assume AWS Roles that have External IDs.
Fixes #541 
This required a PR in the signer library https://github.com/aws/aws-msk-iam-sasl-signer-go/pull/25 and a subsequent release: https://github.com/aws/aws-msk-iam-sasl-signer-go/releases/tag/v1.0.2
Tested with atlantis:
```
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI
│ configuration:
│  - mongey/kafka in /tmp/dgamba/provider
│ 
│ The behavior may therefore not match any released version of the provider
│ and applying changes may cause the state to become incompatible with
│ published releases.
╵
kafka_topic.this["test-topic-3"]: Creating...
kafka_topic.this["test-topic-1"]: Creating...
kafka_topic.this["test-topic-2"]: Creating... …
```

Add sasl_aws_external_id as an additional provider parameter

---

Dockerfile
docker-compose.testacc.yaml
kafka/client.go
kafka/config.go
kafka/provider.go
kafka/topic.go

Based on https://github.com/Mongey/terraform-provider-kafka/pull/451 by @iamnotabout .
This PR fixes compatibility by omitting `cleanup.policy` which can't be changed in MSK Serverless.
Check for MSK Serverless based off DNS of the brokers (AWS mentions the pattern DNS prefix `kafka-serverless.Region.amazonaws.com` in their [instructions for connecting across VPCs](https://aws.amazon.com/blogs/big-data/secure-connectivity-patterns-for-amazon-msk-serverless-cross-account-access/#:~:text=As%20discussed%20earlier,%20the%20bootstrap%20server%20FQDN%20format%20is); I've seen it [elsewhere](https://www.google.com/search?q=kafka-serverless.Region.amazonaws.com) too). It seems like a reliable source to distinguish an MSK serverless connection.
Pending: testing
closes …

Fix msk serverless compatibility

---

kafka/client.go
kafka/config.go
kafka/config_test.go
kafka/topic.go
kafka/topic_test.go

When using this provider against AWS MSK Serverless we often get a perpetual change on the `segment.bytes` configuration. The kafka terraform provider wants to reset the value to `null`. From what I can tell, this probably occurs when AWS MSK Serverless sets `segment.bytes` to a non default value. This results in a perpetual change in the terraform plan since `segment.bytes` is a managed property set by AWS (see [Configuration properties for MSK Serverless clusters](https://docs.aws.amazon.com/msk/latest/developerguide/serverless-config.html)).
An `ignore_changes` is inappropriate here since one would have to ignore the complete topic configuration, which may be desirable to change.
This change fixes the perpetual plan by removing the `segment.bytes` configuration in the case of MSK …

Remove `segment.bytes` from AWS MSK Serverless response
